application: taiwan-py
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30s"

libraries:
- name: jinja2
  version: "latest"
- name: lxml
  version: "latest"

handlers:

- url: /$
  static_files: build/index.html
  upload: build/index.html

# index files
- url: /(.+)/
  static_files: build/\1/index.html
  upload: build/(.+)/index.html

- url: /
  static_dir: build


